export * as authService from './auth';
export * as paperService from './paper';
export * as dashboardService from './dashboard';
export * as filterService from './filter';
export * as searchService from './search';
export * as collectService from './collect';
export * as docService from './doc';
export * as auditService from './audit';
export * as questionService from './question';
export * as qualityService from './quality';
export * as compositionService from './composition';
export * as errorService from './error';
export { default as api } from './api';
